apiVersion: v1
kind: Secret
metadata:
  name: aws-credentials
  namespace: jenkins
type: Opaque
data:
  credentials: W2RlZmF1bHRdCmF3c19hY2Nlc3Nfa2V5X2lkID0gUVVrSlFWSTBOazNNbE1OQXBNVDB4VFdFbz0KYXdzX3NlY3JldF9hY2Nlc3Nfa2V5ID0gWVVsTm5Obll4YllYcFE5RkpyOVROUkZjVVFSYjJ4S1RVVnZSVTFhTURZeVpTVlR1Y1E9CnJlZ2lvbiA9IGRYTXRaR0ZzZEMweA==
