rbac:
  enabled: true

serviceAccount:
  create: true
  name: argocd-image-updater
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::129734005271:role/eks_argocd-image-updater

config:
  registries:
  - name: ECR
    api_url: https://129734005271.dkr.ecr.us-east-1.amazonaws.com
    prefix: 129734005271.dkr.ecr.us-east-1.amazonaws.com
    ping: yes
    insecure: no
    credentials: ext:/scripts/auth.sh
    credsexpire: 10h

authScripts:
  enabled: true
  scripts:
    auth.sh: |
      #!/bin/bash
      aws ecr get-authorization-token --region us-east-1 --output text --query 'authorizationData[].authorizationToken' | base64 -d
