apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argocd-image-updater
  namespace: argocd
  annotations:
    argocd-image-updater.argoproj.io/nodejs.update-strategy: digest
    argocd-image-updater.argoproj.io/nodejs.pull-secret: pullsecret:argocd/argocd-ecr-secret
    argocd-image-updater.argoproj.io/nodejs.allow-tags: "regexp:^v[0-9]+\\.[0-9]+\\.[0-9]+$"
    argocd-image-updater.argoproj.io/nodejs: 129734005271.dkr.ecr.us-east-1.amazonaws.com/az3_app:v1.0.0c
spec:
  destination:
    namespace: argocd
    server: https://kubernetes.default.svc
  project: 'default'
  source:
    helm: {}
    path: argo-cd/argocd-image-updater/helm/image-updater
    repoURL: https://github.com/abdulrahmanalaa123/DEVOPS_CAPSTONE.git
    targetRevision: feat/node-app
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      allowEmpty: false
    syncOptions: []
  revisionHistoryLimit: 3
