apiVersion: v1
kind: Secret
metadata:
  name: argocd-ecr-secret
  namespace: argocd
  labels:
    argocd.argoproj.io/secret-type: repository
type: Opaque
stringData:
  type: ecr
  url: 129734005271.dkr.ecr.us-east-1.amazonaws.com
  region: us-east-1
