apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: jenkins-volumes
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/abdulrahmanalaa123/DEVOPS_CAPSTONE'
    targetRevision: add_ingress
    path: jenkins/manifests
  destination:
    server: https://kubernetes.default.svc
    namespace: jenkins
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
