registries:
- name: ECR
  api_url: https://129734005271.dkr.ecr.us-east-1.amazonaws.com
  prefix: 129734005271.dkr.ecr.us-east-1.amazonaws.com
  ping: yes
  insecure: false
  credentials: awsecr
  credsexpire: 10h

gitCommitUser: ArgoCD Image Updater
gitCommitEmail: argocd-image-updater@example.com
gitCommitTemplate: "chore: update image to {{.NewVersion}}"

gitCreds:
  # Use the existing git-creds secret
  secret:
    name: git-creds
    create: false

# Using IAM Role with service account
serviceAccount:
  create: true
  name: argocd-image-updater
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::129734005271:role/eks_argocd-image-updater

# Add AWS environment variables for the pod
extraEnv:
- name: AWS_REGION
  value: "us-east-1"
- name: AWS_SDK_LOAD_CONFIG
  value: "true"

authScripts:
  enabled: true
  scripts:
    auth.sh: |
      #!/bin/sh
      aws ecr --region "us-east-1" get-authorization-token --output text --query 'authorizationData[].authorizationToken' | base64 -d
